import './bootstrap';
import './pages/layout';
import './pages/user';
import './pages/loading';
import './pages/chart'
import './pages/anomaly-log';
import './pages/matrix';
import './pages/program-utilization';
import './pages/transaction-detail';
import './pages/activity-log';
import './pages/export-modal';